// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"context"
	"github.com/parish/internal/domain"
	"sync"
	"time"
)

// Ensure, that ScheduleRepositoryMock does implement ScheduleRepository.
// If this is not the case, regenerate this file with moq.
var _ ScheduleRepository = &ScheduleRepositoryMock{}

// ScheduleRepositoryMock is a mock implementation of ScheduleRepository.
//
//	func TestSomethingThatUsesScheduleRepository(t *testing.T) {
//
//		// make and configure a mocked ScheduleRepository
//		mockedScheduleRepository := &ScheduleRepositoryMock{
//			GetFunc: func(ctx context.Context) (*domain.Schedule, error) {
//				panic("mock out the Get method")
//			},
//			PutFunc: func(ctx context.Context, schedule *domain.Schedule) error {
//				panic("mock out the Put method")
//			},
//		}
//
//		// use mockedScheduleRepository in code that requires ScheduleRepository
//		// and then make assertions.
//
//	}
type ScheduleRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) (*domain.Schedule, error)

	// PutFunc mocks the Put method.
	PutFunc func(ctx context.Context, schedule *domain.Schedule) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Schedule is the schedule argument value.
			Schedule *domain.Schedule
		}
	}
	lockGet sync.RWMutex
	lockPut sync.RWMutex
}

// Get calls GetFunc.
func (mock *ScheduleRepositoryMock) Get(ctx context.Context) (*domain.Schedule, error) {
	if mock.GetFunc == nil {
		panic("ScheduleRepositoryMock.GetFunc: method is nil but ScheduleRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedScheduleRepository.GetCalls())
func (mock *ScheduleRepositoryMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *ScheduleRepositoryMock) Put(ctx context.Context, schedule *domain.Schedule) error {
	if mock.PutFunc == nil {
		panic("ScheduleRepositoryMock.PutFunc: method is nil but ScheduleRepository.Put was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Schedule *domain.Schedule
	}{
		Ctx:      ctx,
		Schedule: schedule,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(ctx, schedule)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedScheduleRepository.PutCalls())
func (mock *ScheduleRepositoryMock) PutCalls() []struct {
	Ctx      context.Context
	Schedule *domain.Schedule
} {
	var calls []struct {
		Ctx      context.Context
		Schedule *domain.Schedule
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}

// Ensure, that ParishGroupRepositoryMock does implement ParishGroupRepository.
// If this is not the case, regenerate this file with moq.
var _ ParishGroupRepository = &ParishGroupRepositoryMock{}

// ParishGroupRepositoryMock is a mock implementation of ParishGroupRepository.
//
//	func TestSomethingThatUsesParishGroupRepository(t *testing.T) {
//
//		// make and configure a mocked ParishGroupRepository
//		mockedParishGroupRepository := &ParishGroupRepositoryMock{
//			CreateFunc: func(ctx context.Context, group *domain.ParishGroup) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*domain.ParishGroup, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.ParishGroup, error) {
//				panic("mock out the List method")
//			},
//			ListByDateRangeFunc: func(ctx context.Context, start time.Time, end time.Time) ([]*domain.ParishGroup, error) {
//				panic("mock out the ListByDateRange method")
//			},
//			UpdateFunc: func(ctx context.Context, group *domain.ParishGroup) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedParishGroupRepository in code that requires ParishGroupRepository
//		// and then make assertions.
//
//	}
type ParishGroupRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, group *domain.ParishGroup) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*domain.ParishGroup, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.ParishGroup, error)

	// ListByDateRangeFunc mocks the ListByDateRange method.
	ListByDateRangeFunc func(ctx context.Context, start time.Time, end time.Time) ([]*domain.ParishGroup, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, group *domain.ParishGroup) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Group is the group argument value.
			Group *domain.ParishGroup
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByDateRange holds details about calls to the ListByDateRange method.
		ListByDateRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Group is the group argument value.
			Group *domain.ParishGroup
		}
	}
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockGet             sync.RWMutex
	lockList            sync.RWMutex
	lockListByDateRange sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ParishGroupRepositoryMock) Create(ctx context.Context, group *domain.ParishGroup) error {
	if mock.CreateFunc == nil {
		panic("ParishGroupRepositoryMock.CreateFunc: method is nil but ParishGroupRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Group *domain.ParishGroup
	}{
		Ctx:   ctx,
		Group: group,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, group)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedParishGroupRepository.CreateCalls())
func (mock *ParishGroupRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Group *domain.ParishGroup
} {
	var calls []struct {
		Ctx   context.Context
		Group *domain.ParishGroup
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ParishGroupRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("ParishGroupRepositoryMock.DeleteFunc: method is nil but ParishGroupRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedParishGroupRepository.DeleteCalls())
func (mock *ParishGroupRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ParishGroupRepositoryMock) Get(ctx context.Context, id string) (*domain.ParishGroup, error) {
	if mock.GetFunc == nil {
		panic("ParishGroupRepositoryMock.GetFunc: method is nil but ParishGroupRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedParishGroupRepository.GetCalls())
func (mock *ParishGroupRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ParishGroupRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.ParishGroup, error) {
	if mock.ListFunc == nil {
		panic("ParishGroupRepositoryMock.ListFunc: method is nil but ParishGroupRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedParishGroupRepository.ListCalls())
func (mock *ParishGroupRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByDateRange calls ListByDateRangeFunc.
func (mock *ParishGroupRepositoryMock) ListByDateRange(ctx context.Context, start time.Time, end time.Time) ([]*domain.ParishGroup, error) {
	if mock.ListByDateRangeFunc == nil {
		panic("ParishGroupRepositoryMock.ListByDateRangeFunc: method is nil but ParishGroupRepository.ListByDateRange was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}{
		Ctx:   ctx,
		Start: start,
		End:   end,
	}
	mock.lockListByDateRange.Lock()
	mock.calls.ListByDateRange = append(mock.calls.ListByDateRange, callInfo)
	mock.lockListByDateRange.Unlock()
	return mock.ListByDateRangeFunc(ctx, start, end)
}

// ListByDateRangeCalls gets all the calls that were made to ListByDateRange.
// Check the length with:
//
//	len(mockedParishGroupRepository.ListByDateRangeCalls())
func (mock *ParishGroupRepositoryMock) ListByDateRangeCalls() []struct {
	Ctx   context.Context
	Start time.Time
	End   time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}
	mock.lockListByDateRange.RLock()
	calls = mock.calls.ListByDateRange
	mock.lockListByDateRange.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ParishGroupRepositoryMock) Update(ctx context.Context, group *domain.ParishGroup) error {
	if mock.UpdateFunc == nil {
		panic("ParishGroupRepositoryMock.UpdateFunc: method is nil but ParishGroupRepository.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Group *domain.ParishGroup
	}{
		Ctx:   ctx,
		Group: group,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, group)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedParishGroupRepository.UpdateCalls())
func (mock *ParishGroupRepositoryMock) UpdateCalls() []struct {
	Ctx   context.Context
	Group *domain.ParishGroup
} {
	var calls []struct {
		Ctx   context.Context
		Group *domain.ParishGroup
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that EventRepositoryMock does implement EventRepository.
// If this is not the case, regenerate this file with moq.
var _ EventRepository = &EventRepositoryMock{}

// EventRepositoryMock is a mock implementation of EventRepository.
//
//	func TestSomethingThatUsesEventRepository(t *testing.T) {
//
//		// make and configure a mocked EventRepository
//		mockedEventRepository := &EventRepositoryMock{
//			CreateFunc: func(ctx context.Context, event *domain.Event) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*domain.Event, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.Event, error) {
//				panic("mock out the List method")
//			},
//			ListByDateRangeFunc: func(ctx context.Context, start time.Time, end time.Time) ([]*domain.Event, error) {
//				panic("mock out the ListByDateRange method")
//			},
//			UpdateFunc: func(ctx context.Context, event *domain.Event) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedEventRepository in code that requires EventRepository
//		// and then make assertions.
//
//	}
type EventRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, event *domain.Event) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*domain.Event, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.Event, error)

	// ListByDateRangeFunc mocks the ListByDateRange method.
	ListByDateRangeFunc func(ctx context.Context, start time.Time, end time.Time) ([]*domain.Event, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, event *domain.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *domain.Event
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByDateRange holds details about calls to the ListByDateRange method.
		ListByDateRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *domain.Event
		}
	}
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockGet             sync.RWMutex
	lockList            sync.RWMutex
	lockListByDateRange sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *EventRepositoryMock) Create(ctx context.Context, event *domain.Event) error {
	if mock.CreateFunc == nil {
		panic("EventRepositoryMock.CreateFunc: method is nil but EventRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *domain.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, event)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedEventRepository.CreateCalls())
func (mock *EventRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Event *domain.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event *domain.Event
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *EventRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("EventRepositoryMock.DeleteFunc: method is nil but EventRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEventRepository.DeleteCalls())
func (mock *EventRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *EventRepositoryMock) Get(ctx context.Context, id string) (*domain.Event, error) {
	if mock.GetFunc == nil {
		panic("EventRepositoryMock.GetFunc: method is nil but EventRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedEventRepository.GetCalls())
func (mock *EventRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *EventRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.Event, error) {
	if mock.ListFunc == nil {
		panic("EventRepositoryMock.ListFunc: method is nil but EventRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedEventRepository.ListCalls())
func (mock *EventRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByDateRange calls ListByDateRangeFunc.
func (mock *EventRepositoryMock) ListByDateRange(ctx context.Context, start time.Time, end time.Time) ([]*domain.Event, error) {
	if mock.ListByDateRangeFunc == nil {
		panic("EventRepositoryMock.ListByDateRangeFunc: method is nil but EventRepository.ListByDateRange was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}{
		Ctx:   ctx,
		Start: start,
		End:   end,
	}
	mock.lockListByDateRange.Lock()
	mock.calls.ListByDateRange = append(mock.calls.ListByDateRange, callInfo)
	mock.lockListByDateRange.Unlock()
	return mock.ListByDateRangeFunc(ctx, start, end)
}

// ListByDateRangeCalls gets all the calls that were made to ListByDateRange.
// Check the length with:
//
//	len(mockedEventRepository.ListByDateRangeCalls())
func (mock *EventRepositoryMock) ListByDateRangeCalls() []struct {
	Ctx   context.Context
	Start time.Time
	End   time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}
	mock.lockListByDateRange.RLock()
	calls = mock.calls.ListByDateRange
	mock.lockListByDateRange.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *EventRepositoryMock) Update(ctx context.Context, event *domain.Event) error {
	if mock.UpdateFunc == nil {
		panic("EventRepositoryMock.UpdateFunc: method is nil but EventRepository.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *domain.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, event)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedEventRepository.UpdateCalls())
func (mock *EventRepositoryMock) UpdateCalls() []struct {
	Ctx   context.Context
	Event *domain.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event *domain.Event
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that MaterialRepositoryMock does implement MaterialRepository.
// If this is not the case, regenerate this file with moq.
var _ MaterialRepository = &MaterialRepositoryMock{}

// MaterialRepositoryMock is a mock implementation of MaterialRepository.
//
//	func TestSomethingThatUsesMaterialRepository(t *testing.T) {
//
//		// make and configure a mocked MaterialRepository
//		mockedMaterialRepository := &MaterialRepositoryMock{
//			CreateFunc: func(ctx context.Context, material *domain.Material) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*domain.Material, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.Material, error) {
//				panic("mock out the List method")
//			},
//			ListByDateRangeFunc: func(ctx context.Context, start time.Time, end time.Time) ([]*domain.Material, error) {
//				panic("mock out the ListByDateRange method")
//			},
//			ListByLabelFunc: func(ctx context.Context, label string, limit int, offset int) ([]*domain.Material, error) {
//				panic("mock out the ListByLabel method")
//			},
//			ListByTypeFunc: func(ctx context.Context, materialType string, limit int, offset int) ([]*domain.Material, error) {
//				panic("mock out the ListByType method")
//			},
//			UpdateFunc: func(ctx context.Context, material *domain.Material) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedMaterialRepository in code that requires MaterialRepository
//		// and then make assertions.
//
//	}
type MaterialRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, material *domain.Material) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*domain.Material, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.Material, error)

	// ListByDateRangeFunc mocks the ListByDateRange method.
	ListByDateRangeFunc func(ctx context.Context, start time.Time, end time.Time) ([]*domain.Material, error)

	// ListByLabelFunc mocks the ListByLabel method.
	ListByLabelFunc func(ctx context.Context, label string, limit int, offset int) ([]*domain.Material, error)

	// ListByTypeFunc mocks the ListByType method.
	ListByTypeFunc func(ctx context.Context, materialType string, limit int, offset int) ([]*domain.Material, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, material *domain.Material) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Material is the material argument value.
			Material *domain.Material
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByDateRange holds details about calls to the ListByDateRange method.
		ListByDateRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
		}
		// ListByLabel holds details about calls to the ListByLabel method.
		ListByLabel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Label is the label argument value.
			Label string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListByType holds details about calls to the ListByType method.
		ListByType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaterialType is the materialType argument value.
			MaterialType string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Material is the material argument value.
			Material *domain.Material
		}
	}
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockGet             sync.RWMutex
	lockList            sync.RWMutex
	lockListByDateRange sync.RWMutex
	lockListByLabel     sync.RWMutex
	lockListByType      sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MaterialRepositoryMock) Create(ctx context.Context, material *domain.Material) error {
	if mock.CreateFunc == nil {
		panic("MaterialRepositoryMock.CreateFunc: method is nil but MaterialRepository.Create was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Material *domain.Material
	}{
		Ctx:      ctx,
		Material: material,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, material)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedMaterialRepository.CreateCalls())
func (mock *MaterialRepositoryMock) CreateCalls() []struct {
	Ctx      context.Context
	Material *domain.Material
} {
	var calls []struct {
		Ctx      context.Context
		Material *domain.Material
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *MaterialRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("MaterialRepositoryMock.DeleteFunc: method is nil but MaterialRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedMaterialRepository.DeleteCalls())
func (mock *MaterialRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MaterialRepositoryMock) Get(ctx context.Context, id string) (*domain.Material, error) {
	if mock.GetFunc == nil {
		panic("MaterialRepositoryMock.GetFunc: method is nil but MaterialRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedMaterialRepository.GetCalls())
func (mock *MaterialRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *MaterialRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.Material, error) {
	if mock.ListFunc == nil {
		panic("MaterialRepositoryMock.ListFunc: method is nil but MaterialRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedMaterialRepository.ListCalls())
func (mock *MaterialRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByDateRange calls ListByDateRangeFunc.
func (mock *MaterialRepositoryMock) ListByDateRange(ctx context.Context, start time.Time, end time.Time) ([]*domain.Material, error) {
	if mock.ListByDateRangeFunc == nil {
		panic("MaterialRepositoryMock.ListByDateRangeFunc: method is nil but MaterialRepository.ListByDateRange was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}{
		Ctx:   ctx,
		Start: start,
		End:   end,
	}
	mock.lockListByDateRange.Lock()
	mock.calls.ListByDateRange = append(mock.calls.ListByDateRange, callInfo)
	mock.lockListByDateRange.Unlock()
	return mock.ListByDateRangeFunc(ctx, start, end)
}

// ListByDateRangeCalls gets all the calls that were made to ListByDateRange.
// Check the length with:
//
//	len(mockedMaterialRepository.ListByDateRangeCalls())
func (mock *MaterialRepositoryMock) ListByDateRangeCalls() []struct {
	Ctx   context.Context
	Start time.Time
	End   time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Start time.Time
		End   time.Time
	}
	mock.lockListByDateRange.RLock()
	calls = mock.calls.ListByDateRange
	mock.lockListByDateRange.RUnlock()
	return calls
}

// ListByLabel calls ListByLabelFunc.
func (mock *MaterialRepositoryMock) ListByLabel(ctx context.Context, label string, limit int, offset int) ([]*domain.Material, error) {
	if mock.ListByLabelFunc == nil {
		panic("MaterialRepositoryMock.ListByLabelFunc: method is nil but MaterialRepository.ListByLabel was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Label  string
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Label:  label,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListByLabel.Lock()
	mock.calls.ListByLabel = append(mock.calls.ListByLabel, callInfo)
	mock.lockListByLabel.Unlock()
	return mock.ListByLabelFunc(ctx, label, limit, offset)
}

// ListByLabelCalls gets all the calls that were made to ListByLabel.
// Check the length with:
//
//	len(mockedMaterialRepository.ListByLabelCalls())
func (mock *MaterialRepositoryMock) ListByLabelCalls() []struct {
	Ctx    context.Context
	Label  string
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Label  string
		Limit  int
		Offset int
	}
	mock.lockListByLabel.RLock()
	calls = mock.calls.ListByLabel
	mock.lockListByLabel.RUnlock()
	return calls
}

// ListByType calls ListByTypeFunc.
func (mock *MaterialRepositoryMock) ListByType(ctx context.Context, materialType string, limit int, offset int) ([]*domain.Material, error) {
	if mock.ListByTypeFunc == nil {
		panic("MaterialRepositoryMock.ListByTypeFunc: method is nil but MaterialRepository.ListByType was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		MaterialType string
		Limit        int
		Offset       int
	}{
		Ctx:          ctx,
		MaterialType: materialType,
		Limit:        limit,
		Offset:       offset,
	}
	mock.lockListByType.Lock()
	mock.calls.ListByType = append(mock.calls.ListByType, callInfo)
	mock.lockListByType.Unlock()
	return mock.ListByTypeFunc(ctx, materialType, limit, offset)
}

// ListByTypeCalls gets all the calls that were made to ListByType.
// Check the length with:
//
//	len(mockedMaterialRepository.ListByTypeCalls())
func (mock *MaterialRepositoryMock) ListByTypeCalls() []struct {
	Ctx          context.Context
	MaterialType string
	Limit        int
	Offset       int
} {
	var calls []struct {
		Ctx          context.Context
		MaterialType string
		Limit        int
		Offset       int
	}
	mock.lockListByType.RLock()
	calls = mock.calls.ListByType
	mock.lockListByType.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *MaterialRepositoryMock) Update(ctx context.Context, material *domain.Material) error {
	if mock.UpdateFunc == nil {
		panic("MaterialRepositoryMock.UpdateFunc: method is nil but MaterialRepository.Update was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Material *domain.Material
	}{
		Ctx:      ctx,
		Material: material,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, material)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedMaterialRepository.UpdateCalls())
func (mock *MaterialRepositoryMock) UpdateCalls() []struct {
	Ctx      context.Context
	Material *domain.Material
} {
	var calls []struct {
		Ctx      context.Context
		Material *domain.Material
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that UserRepositoryMock does implement UserRepository.
// If this is not the case, regenerate this file with moq.
var _ UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CreateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*domain.User, error) {
//				panic("mock out the Get method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*domain.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, user *domain.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *domain.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*domain.User, error)

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*domain.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user *domain.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
	}
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockGet        sync.RWMutex
	lockGetByEmail sync.RWMutex
	lockList       sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, user *domain.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryMock.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepository.DeleteCalls())
func (mock *UserRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserRepositoryMock) Get(ctx context.Context, id string) (*domain.User, error) {
	if mock.GetFunc == nil {
		panic("UserRepositoryMock.GetFunc: method is nil but UserRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserRepository.GetCalls())
func (mock *UserRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepositoryMock) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepositoryMock.GetByEmailFunc: method is nil but UserRepository.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetByEmailCalls())
func (mock *UserRepositoryMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
	if mock.ListFunc == nil {
		panic("UserRepositoryMock.ListFunc: method is nil but UserRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepository.ListCalls())
func (mock *UserRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(ctx context.Context, user *domain.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that RoleRepositoryMock does implement RoleRepository.
// If this is not the case, regenerate this file with moq.
var _ RoleRepository = &RoleRepositoryMock{}

// RoleRepositoryMock is a mock implementation of RoleRepository.
//
//	func TestSomethingThatUsesRoleRepository(t *testing.T) {
//
//		// make and configure a mocked RoleRepository
//		mockedRoleRepository := &RoleRepositoryMock{
//			CreateFunc: func(ctx context.Context, role *domain.Role) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*domain.Role, error) {
//				panic("mock out the Get method")
//			},
//			GetByNameFunc: func(ctx context.Context, name string) (*domain.Role, error) {
//				panic("mock out the GetByName method")
//			},
//			GetMultipleFunc: func(ctx context.Context, ids []string) ([]*domain.Role, error) {
//				panic("mock out the GetMultiple method")
//			},
//			ListFunc: func(ctx context.Context, limit int, offset int) ([]*domain.Role, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, role *domain.Role) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRoleRepository in code that requires RoleRepository
//		// and then make assertions.
//
//	}
type RoleRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, role *domain.Role) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*domain.Role, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, name string) (*domain.Role, error)

	// GetMultipleFunc mocks the GetMultiple method.
	GetMultipleFunc func(ctx context.Context, ids []string) ([]*domain.Role, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, limit int, offset int) ([]*domain.Role, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, role *domain.Role) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Role is the role argument value.
			Role *domain.Role
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetMultiple holds details about calls to the GetMultiple method.
		GetMultiple []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ids is the ids argument value.
			Ids []string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Role is the role argument value.
			Role *domain.Role
		}
	}
	lockCreate      sync.RWMutex
	lockDelete      sync.RWMutex
	lockGet         sync.RWMutex
	lockGetByName   sync.RWMutex
	lockGetMultiple sync.RWMutex
	lockList        sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RoleRepositoryMock) Create(ctx context.Context, role *domain.Role) error {
	if mock.CreateFunc == nil {
		panic("RoleRepositoryMock.CreateFunc: method is nil but RoleRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Role *domain.Role
	}{
		Ctx:  ctx,
		Role: role,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, role)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRoleRepository.CreateCalls())
func (mock *RoleRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	Role *domain.Role
} {
	var calls []struct {
		Ctx  context.Context
		Role *domain.Role
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RoleRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("RoleRepositoryMock.DeleteFunc: method is nil but RoleRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRoleRepository.DeleteCalls())
func (mock *RoleRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RoleRepositoryMock) Get(ctx context.Context, id string) (*domain.Role, error) {
	if mock.GetFunc == nil {
		panic("RoleRepositoryMock.GetFunc: method is nil but RoleRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRoleRepository.GetCalls())
func (mock *RoleRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *RoleRepositoryMock) GetByName(ctx context.Context, name string) (*domain.Role, error) {
	if mock.GetByNameFunc == nil {
		panic("RoleRepositoryMock.GetByNameFunc: method is nil but RoleRepository.GetByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedRoleRepository.GetByNameCalls())
func (mock *RoleRepositoryMock) GetByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// GetMultiple calls GetMultipleFunc.
func (mock *RoleRepositoryMock) GetMultiple(ctx context.Context, ids []string) ([]*domain.Role, error) {
	if mock.GetMultipleFunc == nil {
		panic("RoleRepositoryMock.GetMultipleFunc: method is nil but RoleRepository.GetMultiple was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ids []string
	}{
		Ctx: ctx,
		Ids: ids,
	}
	mock.lockGetMultiple.Lock()
	mock.calls.GetMultiple = append(mock.calls.GetMultiple, callInfo)
	mock.lockGetMultiple.Unlock()
	return mock.GetMultipleFunc(ctx, ids)
}

// GetMultipleCalls gets all the calls that were made to GetMultiple.
// Check the length with:
//
//	len(mockedRoleRepository.GetMultipleCalls())
func (mock *RoleRepositoryMock) GetMultipleCalls() []struct {
	Ctx context.Context
	Ids []string
} {
	var calls []struct {
		Ctx context.Context
		Ids []string
	}
	mock.lockGetMultiple.RLock()
	calls = mock.calls.GetMultiple
	mock.lockGetMultiple.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *RoleRepositoryMock) List(ctx context.Context, limit int, offset int) ([]*domain.Role, error) {
	if mock.ListFunc == nil {
		panic("RoleRepositoryMock.ListFunc: method is nil but RoleRepository.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedRoleRepository.ListCalls())
func (mock *RoleRepositoryMock) ListCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RoleRepositoryMock) Update(ctx context.Context, role *domain.Role) error {
	if mock.UpdateFunc == nil {
		panic("RoleRepositoryMock.UpdateFunc: method is nil but RoleRepository.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Role *domain.Role
	}{
		Ctx:  ctx,
		Role: role,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, role)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRoleRepository.UpdateCalls())
func (mock *RoleRepositoryMock) UpdateCalls() []struct {
	Ctx  context.Context
	Role *domain.Role
} {
	var calls []struct {
		Ctx  context.Context
		Role *domain.Role
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
