// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cache

import (
	"context"
	"sync"
	"time"
)

// Ensure, that CacheMock does implement Cache.
// If this is not the case, regenerate this file with moq.
var _ Cache = &CacheMock{}

// CacheMock is a mock implementation of Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked Cache
//		mockedCache := &CacheMock{
//			DelFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Del method")
//			},
//			ExpireFunc: func(ctx context.Context, key string, ttl time.Duration) error {
//				panic("mock out the Expire method")
//			},
//			GetFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, key string, value string, ttl time.Duration) error {
//				panic("mock out the Set method")
//			},
//			ZAddFunc: func(ctx context.Context, key string, score float64, member string) error {
//				panic("mock out the ZAdd method")
//			},
//			ZCardFunc: func(ctx context.Context, key string) (int64, error) {
//				panic("mock out the ZCard method")
//			},
//			ZRemRangeByScoreFunc: func(ctx context.Context, key string, min string, max string) error {
//				panic("mock out the ZRemRangeByScore method")
//			},
//		}
//
//		// use mockedCache in code that requires Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, key string) error

	// ExpireFunc mocks the Expire method.
	ExpireFunc func(ctx context.Context, key string, ttl time.Duration) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (string, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value string, ttl time.Duration) error

	// ZAddFunc mocks the ZAdd method.
	ZAddFunc func(ctx context.Context, key string, score float64, member string) error

	// ZCardFunc mocks the ZCard method.
	ZCardFunc func(ctx context.Context, key string) (int64, error)

	// ZRemRangeByScoreFunc mocks the ZRemRangeByScore method.
	ZRemRangeByScoreFunc func(ctx context.Context, key string, min string, max string) error

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Expire holds details about calls to the Expire method.
		Expire []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// ZAdd holds details about calls to the ZAdd method.
		ZAdd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Score is the score argument value.
			Score float64
			// Member is the member argument value.
			Member string
		}
		// ZCard holds details about calls to the ZCard method.
		ZCard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// ZRemRangeByScore holds details about calls to the ZRemRangeByScore method.
		ZRemRangeByScore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Min is the min argument value.
			Min string
			// Max is the max argument value.
			Max string
		}
	}
	lockDel              sync.RWMutex
	lockExpire           sync.RWMutex
	lockGet              sync.RWMutex
	lockSet              sync.RWMutex
	lockZAdd             sync.RWMutex
	lockZCard            sync.RWMutex
	lockZRemRangeByScore sync.RWMutex
}

// Del calls DelFunc.
func (mock *CacheMock) Del(ctx context.Context, key string) error {
	if mock.DelFunc == nil {
		panic("CacheMock.DelFunc: method is nil but Cache.Del was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	return mock.DelFunc(ctx, key)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedCache.DelCalls())
func (mock *CacheMock) DelCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// Expire calls ExpireFunc.
func (mock *CacheMock) Expire(ctx context.Context, key string, ttl time.Duration) error {
	if mock.ExpireFunc == nil {
		panic("CacheMock.ExpireFunc: method is nil but Cache.Expire was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}{
		Ctx: ctx,
		Key: key,
		TTL: ttl,
	}
	mock.lockExpire.Lock()
	mock.calls.Expire = append(mock.calls.Expire, callInfo)
	mock.lockExpire.Unlock()
	return mock.ExpireFunc(ctx, key, ttl)
}

// ExpireCalls gets all the calls that were made to Expire.
// Check the length with:
//
//	len(mockedCache.ExpireCalls())
func (mock *CacheMock) ExpireCalls() []struct {
	Ctx context.Context
	Key string
	TTL time.Duration
} {
	var calls []struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}
	mock.lockExpire.RLock()
	calls = mock.calls.Expire
	mock.lockExpire.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *CacheMock) Get(ctx context.Context, key string) (string, error) {
	if mock.GetFunc == nil {
		panic("CacheMock.GetFunc: method is nil but Cache.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCache.GetCalls())
func (mock *CacheMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *CacheMock) Set(ctx context.Context, key string, value string, ttl time.Duration) error {
	if mock.SetFunc == nil {
		panic("CacheMock.SetFunc: method is nil but Cache.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value string
		TTL   time.Duration
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
		TTL:   ttl,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, ttl)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedCache.SetCalls())
func (mock *CacheMock) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value string
	TTL   time.Duration
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value string
		TTL   time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ZAdd calls ZAddFunc.
func (mock *CacheMock) ZAdd(ctx context.Context, key string, score float64, member string) error {
	if mock.ZAddFunc == nil {
		panic("CacheMock.ZAddFunc: method is nil but Cache.ZAdd was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Key    string
		Score  float64
		Member string
	}{
		Ctx:    ctx,
		Key:    key,
		Score:  score,
		Member: member,
	}
	mock.lockZAdd.Lock()
	mock.calls.ZAdd = append(mock.calls.ZAdd, callInfo)
	mock.lockZAdd.Unlock()
	return mock.ZAddFunc(ctx, key, score, member)
}

// ZAddCalls gets all the calls that were made to ZAdd.
// Check the length with:
//
//	len(mockedCache.ZAddCalls())
func (mock *CacheMock) ZAddCalls() []struct {
	Ctx    context.Context
	Key    string
	Score  float64
	Member string
} {
	var calls []struct {
		Ctx    context.Context
		Key    string
		Score  float64
		Member string
	}
	mock.lockZAdd.RLock()
	calls = mock.calls.ZAdd
	mock.lockZAdd.RUnlock()
	return calls
}

// ZCard calls ZCardFunc.
func (mock *CacheMock) ZCard(ctx context.Context, key string) (int64, error) {
	if mock.ZCardFunc == nil {
		panic("CacheMock.ZCardFunc: method is nil but Cache.ZCard was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockZCard.Lock()
	mock.calls.ZCard = append(mock.calls.ZCard, callInfo)
	mock.lockZCard.Unlock()
	return mock.ZCardFunc(ctx, key)
}

// ZCardCalls gets all the calls that were made to ZCard.
// Check the length with:
//
//	len(mockedCache.ZCardCalls())
func (mock *CacheMock) ZCardCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockZCard.RLock()
	calls = mock.calls.ZCard
	mock.lockZCard.RUnlock()
	return calls
}

// ZRemRangeByScore calls ZRemRangeByScoreFunc.
func (mock *CacheMock) ZRemRangeByScore(ctx context.Context, key string, min string, max string) error {
	if mock.ZRemRangeByScoreFunc == nil {
		panic("CacheMock.ZRemRangeByScoreFunc: method is nil but Cache.ZRemRangeByScore was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		Min string
		Max string
	}{
		Ctx: ctx,
		Key: key,
		Min: min,
		Max: max,
	}
	mock.lockZRemRangeByScore.Lock()
	mock.calls.ZRemRangeByScore = append(mock.calls.ZRemRangeByScore, callInfo)
	mock.lockZRemRangeByScore.Unlock()
	return mock.ZRemRangeByScoreFunc(ctx, key, min, max)
}

// ZRemRangeByScoreCalls gets all the calls that were made to ZRemRangeByScore.
// Check the length with:
//
//	len(mockedCache.ZRemRangeByScoreCalls())
func (mock *CacheMock) ZRemRangeByScoreCalls() []struct {
	Ctx context.Context
	Key string
	Min string
	Max string
} {
	var calls []struct {
		Ctx context.Context
		Key string
		Min string
		Max string
	}
	mock.lockZRemRangeByScore.RLock()
	calls = mock.calls.ZRemRangeByScore
	mock.lockZRemRangeByScore.RUnlock()
	return calls
}
